### ISSUE TITLE
Repos with dots in cause GH "Not found" error

### ISSUE THREAD

**Issue by carlevans719** [bradymholt/npm-github-release#2]
Hey thanks for this!

I've noticed that the regex used to extract the repo url from `package.json` fails if there is a dot in the repo name. [This commit](https://github.com/webantic/npm-github-release/commit/02a905460b33dd68ecf6d9568bedef79a73f2d38) resolves the issue.

[here](https://pastebin.com/WSZSrqnp) are some tests. Let me know if you'd like me to raise a PR!

**Comment by bradymholt** [comment]
Thanks @carlevans719 !  Sure, I would gladly accept a PR!
