### ISSUE TITLE
windows failure

### ISSUE THREAD

**Issue by lauhin** [bradymholt/npm-github-release#4]
Hi there,

This script cannot be used on a windows machine. I get multiple errors..:

The first one is that ```process.env.PWD``` is undefined.
I had to fix this by adding the code below to the top of index.js:

```
if (!process.env.PWD) {
  process.env.PWD = process.cwd();
}
```

The second one is that 'grep' is a not known command on windows. :-(

Thanks in advance.

Laurent :-)

**Comment by bradymholt** [comment]
I updated the README to indicate only macOS and Linux being supported here: https://github.com/bradymholt/npm-github-release/commit/b9aed631051dfea5861955f01dbd8e4b8751ffef. I'd welcome a PR to add support for Windows, however.  The grep usage is just part of a simple check to make sure all changes are committed so it could probably be swapped out for something else or use something like this: https://www.npmjs.com/package/git-state.
