### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by ruettenm** [bradymholt/npm-github-release#5]
Hi

github is complaining that your package is using dependencies with security issue. Could you please have a look?

**Comment by bradymholt** [comment]
I'm not sure what or where you are seeing something but I see no [GitHub Security Alerts](https://github.com/bradymholt/npm-github-release/network/alerts).  Closing for now.

**Comment by ruettenm** [comment]
Hi, I received the alert after I pushed something to the repo. Not sure at which time github is executing the checks.

I had to specify the following resolutions for yarn in may package.json.

```
"resolutions": {
        "lodash": "^4.17.13",
        "deep-extend": "^0.5.1"
}
```

Both dependencies are hoisted dependencies from your package:

```
=> Found "lodash@4.17.15"
info Reasons this module exists
   - "inquirer" depends on it
   - Hoisted from "inquirer#lodash"
   - Hoisted from "npm-github-release#inquirer#lodash"

=> Found "deep-extend@0.5.1"
info Reasons this module exists
   - "npm-github-release#octonode" depends on it
   - Hoisted from "npm-github-release#octonode#deep-extend"
```

**Comment by bradymholt** [comment]
Can you show me the error message itself? Also, you said you "pushed something to the repo".  Do you mean you pushed something to one of your repos?

I just did the following and saw no alerts:
- Looked on https://github.com/bradymholt/npm-github-release/network/alerts
- Cloned this repo, made a change and pushed it up.  No alerts.
```
 git-add-commit 'Mod README for testing' -p
+ git add --all :/
+ git commit -m 'Mod README for testing'
[master 3f6a3c5] Mod README for testing
 1 file changed, 2 insertions(+)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 300 bytes | 300.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:bradymholt/npm-github-release.git
   b9aed63..3f6a3c5  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
```
- In an empty directory I created a package.json and ran `npm install npm install npm-github-release`. The only thing I see is 1 low severity vulnerability which `npm audit fix` would not fix ("required manual review").

```
npm WARN @bradymholt/scratch@1.0.0 No description
npm WARN @bradymholt/scratch@1.0.0 No repository field.

+ npm-github-release@0.9.0
updated 1 package and audited 883 packages in 3.013s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by ruettenm** [comment]
yes, i pushed some other changes to my repo and that is why github was analyzing my dependencies.

In the repo I use your package: https://github.com/ruettenm/jira-activity

I just did a rollback with the resolutions and got again the following warnings:
![image](https://user-images.githubusercontent.com/2926623/64864646-e381f100-d637-11e9-8f00-8709eb05c33d.png)

![image](https://user-images.githubusercontent.com/2926623/64864814-33f94e80-d638-11e9-81f4-366f7e853868.png)

![image](https://user-images.githubusercontent.com/2926623/64864880-555a3a80-d638-11e9-9ea6-8a1b40bf5aef.png)

**Comment by ruettenm** [comment]
I guess github is detecting the issue because i also push my **yarn.lock** file into my repo. So github known about all hoisted dependencies.

**Comment by bradymholt** [comment]
Ah, no I see it.  https://github.com/bradymholt/npm-github-release/pull/6 should fix it.  I pushed up version 0.12.0 up to npm as well.  I don't use yarn so if your downstream package installs a lower version of deep-extend you may need to modify your lock file accordingly.

**Comment by ruettenm** [comment]
Yeah, thanks! Version **0.12.0** solves the security issues 👍

And also thanks for your quick reply ;-)
